### ISSUE TITLE
Translation of image alternative text

### ISSUE THREAD

**Issue by nannione** [dmitryd/dd_deepl#11]
It appears that the alternative text for images in the text/media content element is not translated.

**Comment by dmitryd** [comment]
Thanks, I will have a look at it.

**Comment by Teddytrombone** [comment]
Could it be that this problem is true for all kinds of inline records? We have an extension which adds a field to tt_content where a different record type can be added via IRRE. And allthough there are translated "sub" records created, the texts of those records are not handled by `DeeplTranslationService->translateRecord`, only the translated tt_content record.
